### PR TITLE
feat: added list components

### PR DESCRIPTION
**Pull request by Asuraking1n**
feat: added list components

### CODE REVIEW

**Comment by TusharJade** [comment]
Looks good to me just look at sample list type the first two lists content is going out of the box just change that otherwise evrything looks great👍

**Comment by Asuraking1n** [comment]
> Looks good to me just look at sample list type the first two lists content is going out of the box just change that otherwise evrything looks great👍

Sure, I will try to fix it

**Comment by krgarima** [comment]
All your components are in 1 html file. I would suggest putting your components in a more semantic tag like section etc instead of div. This will also make it easy for the reviewer to find any component and it is also a good practice that helps in SEO. It will also make it look more presentable.

**Comment by krgarima** [comment]
nish
Why is this empty?

**Comment by Asuraking1n** [comment]
> All your components are in 1 html file. I would suggest putting your components in a more semantic tag like section etc instead of div. This will also make it easy for the reviewer to find any components and good practice that helps in SEO. Also, it will make it look more presentable.

okay, I will change every div of components container to section, thanks for suggesting

**Comment by Asuraking1n** [comment]
> nish Why is this empty?

I left it empty bcz user can add any component their, thats why i commented components their.

**Comment by krgarima** [comment]
nis
Open your site in Chrome browser. A lot of elements are overlapping in  chrome browser.

**Comment by Asuraking1n** [comment]
> nis Open your site in Chrome browser. A lot of elements are overlapping in chrome browser.

don't know why it showing like this, everything looks fine in my browser

**Comment by krgarima** [comment]
> > nish Why is this empty?
> 
> I left it empty bcz user can add any component their, thats why i commented components their.

Okay

**Pull request merged**
