### PR TITLE
added badge component

### PR DESCRIPTION
**Pull request by Asuraking1n**

### CODE REVIEW

**Review by sakshi006 — COMMENTED** [review]
Looks cool.
Also, you must add some text badges as well.

**Review by kirti2602 — APPROVED** [review]
Looks clean. 
One suggestion would be to properly indent the code in carbon `<iframe>`

**Comment by Asuraking1n** [comment]
> Looks cool. Also, you must add some text badges as well.

Sure, thanks for telling me this,I had no idea that about text badges

**Comment by Asuraking1n** [comment]
> Looks clean. One suggestion would be to properly indent the code in carbon `<iframe>`

Offcourse, I will correct them.thanks

**Pull request merged**
